TARGET		:= set_scart
WIIU_COMMON_DIR := ../../common

BUILD_HBL_ELF	 = 1
BUILD_RPX	 = 1
DEBUG            = 0
LOGGER_IP        =
LOGGER_TCP_PORT	 =

OBJ :=
OBJ += main.o

DEFINES  :=
INCDIRS  := -I.
CFLAGS   :=

CXXFLAGS := -fno-rtti -fno-exceptions
LDFLAGS  :=
LIBS     :=

include $(WIIU_COMMON_DIR)/system/common.mk
